name: Run Einbürgerung Check

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # Grant write access to repository contents

jobs:
  run-check:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Notify run check
        run:  |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=Start check!"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          echo "Chrome version: $CHROME_VERSION"
          DRIVER_VERSION=$(curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$(echo $CHROME_VERSION | cut -d'.' -f1))
          echo "Driver version: DRIVER_VERSION"
          wget -N https://storage.googleapis.com/chrome-for-testing-public/$DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Einbürgerung Check
        run: python einbuergerung-check.py

      - name: Notify run check
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=Go and book your appointment now! \n https://service.berlin.de/terminvereinbarung/termin/all/351180/"

      - name: Commit and push HTML changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add html/
          git commit -m "Add new HTML snapshot of available appointments"
          git push
