name: Run Tests

on:
  pull_request:
    paths:
      - 'lib/**'
      - '.github/workflows/test.yml'
      - 'tests/**'
      - 'einbuergerung_check.py'
      - 'requirements.txt'
      - 'requirements-dev.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          TELEGRAM_BOT_TOKEN: 0000000000:testing
          AWS_ACCESS_KEY_ID: testing
          AWS_SECRET_ACCESS_KEY: testing
          AWS_SECURITY_TOKEN: testing
          AWS_SESSION_TOKEN: testing
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          python -m unittest discover -s tests
